-- SQL Schema for Jano's Combo Digital (Multi-Tenant)
-- You can copy and paste this into the Supabase SQL Editor (https://supabase.com)

-- 1. Create EVENTS Table
CREATE TABLE IF NOT EXISTS public.events (
    id TEXT PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_email TEXT,
    password TEXT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    service_tables BOOLEAN DEFAULT TRUE NOT NULL,
    service_photos BOOLEAN DEFAULT TRUE NOT NULL,
    service_invitation BOOLEAN DEFAULT TRUE NOT NULL,
    service_trivia BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert fallback default event if not exists
INSERT INTO public.events (id, client_name, active)
VALUES ('default', 'Default Event', true)
ON CONFLICT (id) DO NOTHING;

-- 2. Create GUESTS Table
CREATE TABLE IF NOT EXISTS public.guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    first_name TEXT,
    last_name TEXT,
    table_number TEXT DEFAULT 'Sin Mesa',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexing for fast tenant lookup
CREATE INDEX IF NOT EXISTS idx_guests_event_id ON public.guests(event_id);

-- 3. Create CONFIG Table
CREATE TABLE IF NOT EXISTS public.config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_event_key UNIQUE (event_id, key)
);

-- Indexing for configuration lookups
CREATE INDEX IF NOT EXISTS idx_config_event_id_key ON public.config(event_id, key);

-- 4. Create PHOTOS Table
CREATE TABLE IF NOT EXISTS public.photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    guest_name TEXT DEFAULT 'Invitado',
    message TEXT,
    photo_url TEXT NOT NULL,
    approved BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexing for photos lookup and approval status
CREATE INDEX IF NOT EXISTS idx_photos_event_id_approved ON public.photos(event_id, approved);

-- Enable RLS (Row Level Security)
-- Since the server uses the service_role key to bypass RLS, the backend will function perfectly.
-- Keeping RLS enabled prevents any direct unauthorized access using the anon key.

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;

-- 5. Create RSVPS Table
CREATE TABLE IF NOT EXISTS public.rsvps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    attending BOOLEAN NOT NULL,
    companions_count INT DEFAULT 0,
    companions_names TEXT,
    dietary_restrictions TEXT,
    suggested_song TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexing for fast rsvps query by event_id
CREATE INDEX IF NOT EXISTS idx_rsvps_event_id ON public.rsvps(event_id);

-- Enable RLS for RSVPS table
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- 6. Upgrade query for existing events table
ALTER TABLE public.events ADD COLUMN IF NOT EXISTS service_trivia BOOLEAN DEFAULT TRUE NOT NULL;

